// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMfnEmQtrLFZD1YxGeyH2qkiNlza_v8MA',
    appId: '1:880616834513:web:cb9b36c749e38d0c96ccf0',
    messagingSenderId: '880616834513',
    projectId: 'bolt-e5661',
    authDomain: 'bolt-e5661.firebaseapp.com',
    storageBucket: 'bolt-e5661.appspot.com',
    measurementId: 'G-351WTKFQXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtk5ygLMjk0Lisq2RjDJVbBjpwJSHzx1k',
    appId: '1:880616834513:android:d794e67463d70f7c96ccf0',
    messagingSenderId: '880616834513',
    projectId: 'bolt-e5661',
    storageBucket: 'bolt-e5661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rri_NYJAVG353c937ELmxGk_fCW8DAc',
    appId: '1:880616834513:ios:fe9417cacc6ebda996ccf0',
    messagingSenderId: '880616834513',
    projectId: 'bolt-e5661',
    storageBucket: 'bolt-e5661.appspot.com',
    iosClientId: '880616834513-bkf248ueum8sllna8k7vkq6qpc86o1uo.apps.googleusercontent.com',
    iosBundleId: 'com.bolt.bolt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0rri_NYJAVG353c937ELmxGk_fCW8DAc',
    appId: '1:880616834513:ios:fe9417cacc6ebda996ccf0',
    messagingSenderId: '880616834513',
    projectId: 'bolt-e5661',
    storageBucket: 'bolt-e5661.appspot.com',
    iosClientId: '880616834513-bkf248ueum8sllna8k7vkq6qpc86o1uo.apps.googleusercontent.com',
    iosBundleId: 'com.bolt.bolt',
  );
}
